project_id = "kcmtwnzmeelaypolufjf"

[functions.protocol-chat]
verify_jwt = false

[functions.analyze-insights]
verify_jwt = false

[functions.activate-subscription]
verify_jwt = false

[functions.send-sms-reminders]
verify_jwt = false

[functions.send-push-reminders]
verify_jwt = false
